//! Maintenance CLI for generated `bedrock-world` version data.

use bedrock_world::biome::BiomeRegistry;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use xxhash_rust::xxh3::xxh3_64;

type ToolResult<T> = std::result::Result<T, Box<dyn Error>>;

const MAGIC: &[u8; 8] = b"BWRBIO01";
const FORMAT_VERSION: u16 = 1;
const UNKNOWN_NETWORK_VERSION: u32 = u32::MAX;

const HAS_TEMPERATURE: u16 = 1 << 0;
const HAS_DOWNFALL: u16 = 1 << 1;
const HAS_FOLIAGE_SNOW: u16 = 1 << 2;
const HAS_DEPTH: u16 = 1 << 3;
const HAS_SCALE: u16 = 1 << 4;
const HAS_MAP_WATER_COLOR: u16 = 1 << 5;
const HAS_RAIN: u16 = 1 << 6;
const RAIN_VALUE: u16 = 1 << 7;

fn main() {
    if let Err(error) = run() {
        eprintln!("bedrock-world-tool: {error}");
        std::process::exit(1);
    }
}

fn run() -> ToolResult<()> {
    let mut args = env::args().skip(1);
    let Some(group) = args.next() else {
        print_help();
        return Ok(());
    };
    if group == "--help" || group == "-h" || group == "help" {
        print_help();
        return Ok(());
    }
    if group != "biome" {
        return Err(format!("unknown tool group `{group}`; expected `biome`").into());
    }
    let Some(command) = args.next() else {
        print_biome_help();
        return Ok(());
    };
    if command == "--help" || command == "-h" || command == "help" {
        print_biome_help();
        return Ok(());
    }
    let options = parse_options(args.collect())?;
    match command.as_str() {
        "update" => biome_update(&options),
        "pack" => biome_pack(&options),
        "verify" => biome_verify(&options),
        other => Err(format!("unknown biome command `{other}`").into()),
    }
}

fn print_help() {
    println!(
        "bedrock-world-tool\n\nUSAGE:\n  bedrock-world-tool biome <update|pack|verify> [options]\n\nRun `bedrock-world-tool biome help` for biome registry commands."
    );
}

fn print_biome_help() {
    println!(
        "Biome registry maintenance\n\n\
USAGE:\n\
  bedrock-world-tool biome update --input <biomes.json> [metadata options]\n\
  bedrock-world-tool biome pack [--manifest <manifest.json>] [--output <registry.bin>]\n\
  bedrock-world-tool biome verify [--manifest <manifest.json>] [--output <registry.bin>]\n\n\
UPDATE METADATA:\n\
  --minecraft-version <1.26.44.3>   Explicit exact BDS game version\n\
  --network-version <2168>          Explicit protocol version\n\
  --bds-metadata <metadata.json>    Endstone bedrock-server-data metadata; exact build is read from the BDS URL\n\
  --protocol-readme <README.md>     protocol-docs README; Minecraft/Network Version are parsed automatically\n\
  --channel <release|preview>       Provenance label stored with the source snapshot\n\
  --endstone-ref <ref>              Endstone source ref/commit used to export biomes\n\
  --protocol-ref <ref>              protocol-docs ref used for network metadata\n\n\
PATH OVERRIDES:\n\
  --manifest <path>                 Defaults to vendor/biome-registry/manifest.json\n\
  --output <path>                   Defaults to src/biome/registry.bin\n\n\
`update` accepts either Endstone's plain {{name:{{id}}}} biomes.json or a full object containing a `biomes` member. It writes a normalized version snapshot, updates the manifest, rebuilds the binary registry, and verifies the generated bytes with bedrock-world itself."
    );
}

fn parse_options(args: Vec<String>) -> ToolResult<BTreeMap<String, String>> {
    let mut options = BTreeMap::new();
    let mut index = 0_usize;
    while index < args.len() {
        let key = &args[index];
        if !key.starts_with("--") {
            return Err(format!("unexpected positional argument `{key}`").into());
        }
        let Some(value) = args.get(index + 1) else {
            return Err(format!("option `{key}` requires a value").into());
        };
        if value.starts_with("--") {
            return Err(format!("option `{key}` requires a value").into());
        }
        if options.insert(key[2..].to_string(), value.clone()).is_some() {
            return Err(format!("option `{key}` was supplied more than once").into());
        }
        index += 2;
    }
    Ok(options)
}

fn biome_update(options: &BTreeMap<String, String>) -> ToolResult<()> {
    reject_unknown_options(
        options,
        &[
            "input",
            "minecraft-version",
            "network-version",
            "bds-metadata",
            "protocol-readme",
            "channel",
            "endstone-ref",
            "protocol-ref",
            "manifest",
            "output",
        ],
    )?;
    let input = required_path(options, "input")?;
    let manifest_path = option_path(options, "manifest").unwrap_or_else(default_manifest_path);
    let output_path = option_path(options, "output").unwrap_or_else(default_binary_path);
    let input_bytes = fs::read(&input)?;
    let input_json: Value = serde_json::from_slice(&input_bytes)?;

    let bds_version = options
        .get("bds-metadata")
        .map(|path| exact_bds_version_from_metadata(Path::new(path)))
        .transpose()?;
    let protocol = options
        .get("protocol-readme")
        .map(|path| protocol_metadata(Path::new(path)))
        .transpose()?;
    let input_version = input_json
        .get("minecraft_version")
        .and_then(Value::as_str)
        .map(ToOwned::to_owned);
    let explicit_version = options.get("minecraft-version").cloned();
    let protocol_version = protocol.as_ref().and_then(|value| value.minecraft_version.clone());
    let minecraft_version = choose_consistent(
        "Minecraft version",
        [explicit_version, bds_version, protocol_version, input_version],
    )?
    .ok_or("Minecraft version is unknown; pass --minecraft-version, --bds-metadata, or --protocol-readme")?;
    let _ = parse_version_key(&minecraft_version)?;

    let explicit_network = options
        .get("network-version")
        .map(|value| value.parse::<u32>())
        .transpose()?;
    let protocol_network = protocol.as_ref().and_then(|value| value.network_version);
    let input_network = input_json
        .get("network_version")
        .and_then(Value::as_u64)
        .map(u32::try_from)
        .transpose()?;
    let network_version =
        choose_consistent("network version", [explicit_network, protocol_network, input_network])?;

    let biomes_value = input_json.get("biomes").unwrap_or(&input_json);
    let biomes_object = biomes_value
        .as_object()
        .ok_or("Endstone biome input must be a JSON object or contain an object-valued `biomes` member")?;
    let mut biomes = BTreeMap::new();
    let mut ids = BTreeSet::new();
    for (name, value) in biomes_object {
        if name.is_empty() {
            return Err("biome name cannot be empty".into());
        }
        let entry: BiomeSource = serde_json::from_value(value.clone())?;
        if !ids.insert(entry.id) {
            return Err(format!("duplicate biome id {} in source snapshot", entry.id).into());
        }
        validate_optional_floats(name, &entry)?;
        biomes.insert(name.clone(), entry);
    }
    if biomes.is_empty() {
        return Err("refusing to import an empty biome snapshot".into());
    }

    let snapshot = SnapshotSource {
        schema: 1,
        minecraft_version: minecraft_version.clone(),
        network_version,
        source: SourceProvenance {
            channel: options.get("channel").cloned(),
            endstone_ref: options.get("endstone-ref").cloned(),
            protocol_ref: options.get("protocol-ref").cloned(),
        },
        biomes,
    };

    let manifest_dir = manifest_path
        .parent()
        .ok_or("biome manifest path has no parent directory")?;
    let snapshots_dir = manifest_dir.join("snapshots");
    fs::create_dir_all(&snapshots_dir)?;
    let snapshot_filename = format!("{}.json", safe_version_filename(&minecraft_version));
    let snapshot_path = snapshots_dir.join(&snapshot_filename);
    write_json(&snapshot_path, &snapshot)?;

    let mut manifest = load_manifest(&manifest_path)?;
    let relative_path = format!("snapshots/{snapshot_filename}");
    if let Some(entry) = manifest
        .snapshots
        .iter_mut()
        .find(|entry| entry.minecraft_version == minecraft_version)
    {
        entry.file = relative_path;
        entry.network_version = network_version;
    } else {
        manifest.snapshots.push(ManifestSnapshot {
            minecraft_version: minecraft_version.clone(),
            network_version,
            file: relative_path,
        });
    }
    let mut keyed_snapshots = Vec::with_capacity(manifest.snapshots.len());
    for entry in manifest.snapshots {
        keyed_snapshots.push((parse_version_key(&entry.minecraft_version)?, entry));
    }
    keyed_snapshots.sort_by_key(|(key, _)| *key);
    manifest.snapshots = keyed_snapshots
        .into_iter()
        .map(|(_, entry)| entry)
        .collect();
    write_json(&manifest_path, &manifest)?;

    let bytes = pack_manifest(&manifest_path)?;
    write_binary(&output_path, &bytes)?;
    let registry = BiomeRegistry::parse(&bytes)?;
    println!(
        "updated biome registry: version={}, network={}, biomes={}, snapshots={}, output={}",
        minecraft_version,
        network_version
            .map(|value| value.to_string())
            .unwrap_or_else(|| "unknown".to_string()),
        snapshot.biomes.len(),
        registry.snapshot_count(),
        output_path.display()
    );
    Ok(())
}

fn biome_pack(options: &BTreeMap<String, String>) -> ToolResult<()> {
    reject_unknown_options(options, &["manifest", "output"])?;
    let manifest_path = option_path(options, "manifest").unwrap_or_else(default_manifest_path);
    let output_path = option_path(options, "output").unwrap_or_else(default_binary_path);
    let bytes = pack_manifest(&manifest_path)?;
    write_binary(&output_path, &bytes)?;
    let registry = BiomeRegistry::parse(&bytes)?;
    println!(
        "packed {} biome snapshot(s) into {} bytes: {}",
        registry.snapshot_count(),
        bytes.len(),
        output_path.display()
    );
    Ok(())
}

fn biome_verify(options: &BTreeMap<String, String>) -> ToolResult<()> {
    reject_unknown_options(options, &["manifest", "output"])?;
    let manifest_path = option_path(options, "manifest").unwrap_or_else(default_manifest_path);
    let output_path = option_path(options, "output").unwrap_or_else(default_binary_path);
    let actual = fs::read(&output_path)?;
    let registry = BiomeRegistry::parse(&actual)?;
    let expected = pack_manifest(&manifest_path)?;
    if actual != expected {
        return Err(format!(
            "{} is stale: rebuild it with `bedrock-world-tool biome pack`",
            output_path.display()
        )
        .into());
    }
    println!(
        "verified biome registry: snapshots={}, bytes={}",
        registry.snapshot_count(),
        actual.len()
    );
    Ok(())
}

fn pack_manifest(manifest_path: &Path) -> ToolResult<Vec<u8>> {
    let manifest = load_manifest(manifest_path)?;
    if manifest.schema != 1 {
        return Err(format!("unsupported biome manifest schema {}", manifest.schema).into());
    }
    let base = manifest_path
        .parent()
        .ok_or("biome manifest path has no parent directory")?;
    let mut snapshots = Vec::with_capacity(manifest.snapshots.len());
    let mut seen_versions = BTreeSet::new();
    for entry in manifest.snapshots {
        let key = parse_version_key(&entry.minecraft_version)?;
        if !seen_versions.insert(key) {
            return Err(format!(
                "duplicate Minecraft version {} in biome manifest",
                entry.minecraft_version
            )
            .into());
        }
        let source_path = base.join(&entry.file);
        let source: SnapshotSource = serde_json::from_slice(&fs::read(&source_path)?)?;
        if source.schema != 1 {
            return Err(format!(
                "unsupported biome snapshot schema {} in {}",
                source.schema,
                source_path.display()
            )
            .into());
        }
        if source.minecraft_version != entry.minecraft_version {
            return Err(format!(
                "biome manifest version {} does not match snapshot version {} in {}",
                entry.minecraft_version,
                source.minecraft_version,
                source_path.display()
            )
            .into());
        }
        if source.network_version != entry.network_version {
            return Err(format!(
                "biome manifest network version {:?} does not match snapshot {:?} in {}",
                entry.network_version,
                source.network_version,
                source_path.display()
            )
            .into());
        }
        validate_snapshot(&source)?;
        snapshots.push((key, source));
    }
    snapshots.sort_by_key(|(key, _)| *key);
    build_binary(&snapshots)
}

fn build_binary(snapshots: &[([u16; 4], SnapshotSource)]) -> ToolResult<Vec<u8>> {
    let mut names = BTreeSet::<String>::new();
    for (_, snapshot) in snapshots {
        names.extend(snapshot.biomes.keys().cloned());
    }
    let mut string_pool = Vec::new();
    let mut string_locations = BTreeMap::<String, (u32, u16)>::new();
    for name in names {
        let offset = u32::try_from(string_pool.len())?;
        let name_len = u16::try_from(name.len())?;
        string_pool.extend_from_slice(name.as_bytes());
        string_locations.insert(name, (offset, name_len));
    }

    let mut snapshot_records = Vec::<PackedSnapshot>::new();
    let mut biome_records = Vec::<PackedBiome>::new();
    let mut name_index = Vec::<PackedNameIndex>::new();

    for (version, snapshot) in snapshots {
        let biome_start = u32::try_from(biome_records.len())?;
        let name_index_start = u32::try_from(name_index.len())?;
        let mut by_id: Vec<_> = snapshot.biomes.iter().collect();
        by_id.sort_by_key(|(_, biome)| biome.id);
        let mut previous_id = None;
        let mut snapshot_names = Vec::<(u64, String, u32)>::with_capacity(by_id.len());
        for (name, biome) in by_id {
            if previous_id == Some(biome.id) {
                return Err(format!(
                    "duplicate biome id {} in {}",
                    biome.id, snapshot.minecraft_version
                )
                .into());
            }
            previous_id = Some(biome.id);
            let (name_offset, name_len) = *string_locations
                .get(name)
                .ok_or("internal biome string-pool entry is missing")?;
            let absolute_index = u32::try_from(biome_records.len())?;
            biome_records.push(PackedBiome::from_source(biome, name_offset, name_len));
            snapshot_names.push((xxh3_64(name.as_bytes()), name.clone(), absolute_index));
        }
        snapshot_names.sort_by(|left, right| (left.0, &left.1).cmp(&(right.0, &right.1)));
        for (hash, _, biome_index) in snapshot_names {
            name_index.push(PackedNameIndex { hash, biome_index });
        }
        snapshot_records.push(PackedSnapshot {
            version: *version,
            network_version: snapshot.network_version.unwrap_or(UNKNOWN_NETWORK_VERSION),
            biome_start,
            biome_count: u32::try_from(snapshot.biomes.len())?,
            name_index_start,
            name_index_count: u32::try_from(snapshot.biomes.len())?,
        });
    }

    let mut bytes = Vec::new();
    bytes.extend_from_slice(MAGIC);
    bytes.extend_from_slice(&FORMAT_VERSION.to_le_bytes());
    bytes.extend_from_slice(&0_u16.to_le_bytes());
    bytes.extend_from_slice(&u32::try_from(snapshot_records.len())?.to_le_bytes());
    bytes.extend_from_slice(&u32::try_from(biome_records.len())?.to_le_bytes());
    bytes.extend_from_slice(&u32::try_from(name_index.len())?.to_le_bytes());
    bytes.extend_from_slice(&u32::try_from(string_pool.len())?.to_le_bytes());
    for record in snapshot_records {
        record.write(&mut bytes);
    }
    for record in biome_records {
        record.write(&mut bytes);
    }
    for record in name_index {
        record.write(&mut bytes);
    }
    bytes.extend_from_slice(&string_pool);
    BiomeRegistry::parse(&bytes)?;
    Ok(bytes)
}

fn validate_snapshot(snapshot: &SnapshotSource) -> ToolResult<()> {
    let _ = parse_version_key(&snapshot.minecraft_version)?;
    if snapshot.biomes.is_empty() {
        return Err(format!("biome snapshot {} is empty", snapshot.minecraft_version).into());
    }
    let mut ids = BTreeSet::new();
    for (name, biome) in &snapshot.biomes {
        if !ids.insert(biome.id) {
            return Err(format!(
                "duplicate biome id {} in {}",
                biome.id, snapshot.minecraft_version
            )
            .into());
        }
        validate_optional_floats(name, biome)?;
    }
    Ok(())
}

fn validate_optional_floats(name: &str, biome: &BiomeSource) -> ToolResult<()> {
    for (field, value) in [
        ("temperature", biome.temperature),
        ("downfall", biome.downfall),
        ("foliage_snow", biome.foliage_snow),
        ("depth", biome.depth),
        ("scale", biome.scale),
    ] {
        if value.is_some_and(|value| !value.is_finite()) {
            return Err(format!("biome {name} field {field} is not finite").into());
        }
    }
    Ok(())
}

fn choose_consistent<T, const N: usize>(label: &str, values: [Option<T>; N]) -> ToolResult<Option<T>>
where
    T: Clone + PartialEq + std::fmt::Display,
{
    let mut selected = None::<T>;
    for value in values.into_iter().flatten() {
        if let Some(current) = &selected {
            if current != &value {
                return Err(format!("conflicting {label}: {current} != {value}").into());
            }
        } else {
            selected = Some(value);
        }
    }
    Ok(selected)
}

fn exact_bds_version_from_metadata(path: &Path) -> ToolResult<String> {
    let metadata: Value = serde_json::from_slice(&fs::read(path)?)?;
    let binary = metadata
        .get("binary")
        .and_then(Value::as_object)
        .ok_or("BDS metadata is missing `binary`")?;
    let url = ["linux", "windows"]
        .into_iter()
        .find_map(|platform| binary.get(platform)?.get("url")?.as_str())
        .ok_or("BDS metadata contains no Linux or Windows binary URL")?;
    let marker = "bedrock-server-";
    let start = url
        .rfind(marker)
        .map(|index| index + marker.len())
        .ok_or("BDS URL does not contain bedrock-server-<version>.zip")?;
    let version = url[start..]
        .strip_suffix(".zip")
        .ok_or("BDS URL does not end in .zip")?;
    let _ = parse_version_key(version)?;
    Ok(version.to_string())
}

fn protocol_metadata(path: &Path) -> ToolResult<ProtocolMetadata> {
    let text = fs::read_to_string(path)?;
    let mut metadata = ProtocolMetadata::default();
    for line in text.lines() {
        if let Some(value) = line.strip_prefix("- **Minecraft Version:**") {
            metadata.minecraft_version = Some(value.trim().to_string());
        } else if let Some(value) = line.strip_prefix("- **Network Version:**") {
            metadata.network_version = Some(value.trim().parse()?);
        }
    }
    Ok(metadata)
}

fn parse_version_key(version: &str) -> ToolResult<[u16; 4]> {
    let parts: Vec<_> = version.split('.').collect();
    if parts.is_empty() || parts.len() > 4 {
        return Err(format!(
            "Minecraft version `{version}` must have one to four numeric components"
        )
        .into());
    }
    let mut key = [0_u16; 4];
    for (index, part) in parts.iter().enumerate() {
        if part.is_empty() || !part.bytes().all(|byte| byte.is_ascii_digit()) {
            return Err(format!(
                "Minecraft version `{version}` contains a non-numeric component"
            )
            .into());
        }
        key[index] = part.parse()?;
    }
    Ok(key)
}

fn safe_version_filename(version: &str) -> String {
    version
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '_') {
                character
            } else {
                '_'
            }
        })
        .collect()
}

fn load_manifest(path: &Path) -> ToolResult<RegistryManifest> {
    if !path.exists() {
        return Ok(RegistryManifest {
            schema: 1,
            snapshots: Vec::new(),
        });
    }
    Ok(serde_json::from_slice(&fs::read(path)?)?)
}

fn write_json(path: &Path, value: &impl Serialize) -> ToolResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut json = serde_json::to_string_pretty(value)?;
    json.push('\n');
    fs::write(path, json)?;
    Ok(())
}

fn write_binary(path: &Path, bytes: &[u8]) -> ToolResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, bytes)?;
    Ok(())
}

fn reject_unknown_options(options: &BTreeMap<String, String>, allowed: &[&str]) -> ToolResult<()> {
    for key in options.keys() {
        if !allowed.contains(&key.as_str()) {
            return Err(format!("unknown option --{key}").into());
        }
    }
    Ok(())
}

fn required_path(options: &BTreeMap<String, String>, name: &str) -> ToolResult<PathBuf> {
    options
        .get(name)
        .map(PathBuf::from)
        .ok_or_else(|| format!("missing required option --{name}").into())
}

fn option_path(options: &BTreeMap<String, String>, name: &str) -> Option<PathBuf> {
    options.get(name).map(PathBuf::from)
}

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn default_manifest_path() -> PathBuf {
    crate_root().join("vendor/biome-registry/manifest.json")
}

fn default_binary_path() -> PathBuf {
    crate_root().join("src/biome/registry.bin")
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct RegistryManifest {
    schema: u32,
    snapshots: Vec<ManifestSnapshot>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ManifestSnapshot {
    minecraft_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    network_version: Option<u32>,
    file: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct SnapshotSource {
    schema: u32,
    minecraft_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    network_version: Option<u32>,
    #[serde(default)]
    source: SourceProvenance,
    biomes: BTreeMap<String, BiomeSource>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct SourceProvenance {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    channel: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    endstone_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    protocol_ref: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct BiomeSource {
    id: u32,
    #[serde(default)]
    temperature: Option<f32>,
    #[serde(default)]
    downfall: Option<f32>,
    #[serde(default, alias = "foliage snow")]
    foliage_snow: Option<f32>,
    #[serde(default)]
    depth: Option<f32>,
    #[serde(default)]
    scale: Option<f32>,
    #[serde(
        default,
        alias = "map water color ARGB",
        alias = "map_water_color_argb",
        alias = "mapWaterColor"
    )]
    map_water_color: Option<i32>,
    #[serde(default)]
    rain: Option<bool>,
}

#[derive(Debug, Default)]
struct ProtocolMetadata {
    minecraft_version: Option<String>,
    network_version: Option<u32>,
}

struct PackedSnapshot {
    version: [u16; 4],
    network_version: u32,
    biome_start: u32,
    biome_count: u32,
    name_index_start: u32,
    name_index_count: u32,
}

impl PackedSnapshot {
    fn write(self, bytes: &mut Vec<u8>) {
        for component in self.version {
            bytes.extend_from_slice(&component.to_le_bytes());
        }
        bytes.extend_from_slice(&self.network_version.to_le_bytes());
        bytes.extend_from_slice(&self.biome_start.to_le_bytes());
        bytes.extend_from_slice(&self.biome_count.to_le_bytes());
        bytes.extend_from_slice(&self.name_index_start.to_le_bytes());
        bytes.extend_from_slice(&self.name_index_count.to_le_bytes());
    }
}

struct PackedBiome {
    id: u32,
    name_offset: u32,
    name_len: u16,
    flags: u16,
    temperature: f32,
    downfall: f32,
    foliage_snow: f32,
    depth: f32,
    scale: f32,
    map_water_color: i32,
}

impl PackedBiome {
    fn from_source(source: &BiomeSource, name_offset: u32, name_len: u16) -> Self {
        let mut flags = 0_u16;
        if source.temperature.is_some() {
            flags |= HAS_TEMPERATURE;
        }
        if source.downfall.is_some() {
            flags |= HAS_DOWNFALL;
        }
        if source.foliage_snow.is_some() {
            flags |= HAS_FOLIAGE_SNOW;
        }
        if source.depth.is_some() {
            flags |= HAS_DEPTH;
        }
        if source.scale.is_some() {
            flags |= HAS_SCALE;
        }
        if source.map_water_color.is_some() {
            flags |= HAS_MAP_WATER_COLOR;
        }
        if let Some(rain) = source.rain {
            flags |= HAS_RAIN;
            if rain {
                flags |= RAIN_VALUE;
            }
        }
        Self {
            id: source.id,
            name_offset,
            name_len,
            flags,
            temperature: source.temperature.unwrap_or(0.0),
            downfall: source.downfall.unwrap_or(0.0),
            foliage_snow: source.foliage_snow.unwrap_or(0.0),
            depth: source.depth.unwrap_or(0.0),
            scale: source.scale.unwrap_or(0.0),
            map_water_color: source.map_water_color.unwrap_or(0),
        }
    }

    fn write(self, bytes: &mut Vec<u8>) {
        bytes.extend_from_slice(&self.id.to_le_bytes());
        bytes.extend_from_slice(&self.name_offset.to_le_bytes());
        bytes.extend_from_slice(&self.name_len.to_le_bytes());
        bytes.extend_from_slice(&self.flags.to_le_bytes());
        bytes.extend_from_slice(&self.temperature.to_le_bytes());
        bytes.extend_from_slice(&self.downfall.to_le_bytes());
        bytes.extend_from_slice(&self.foliage_snow.to_le_bytes());
        bytes.extend_from_slice(&self.depth.to_le_bytes());
        bytes.extend_from_slice(&self.scale.to_le_bytes());
        bytes.extend_from_slice(&self.map_water_color.to_le_bytes());
        bytes.extend_from_slice(&0_u32.to_le_bytes());
    }
}

struct PackedNameIndex {
    hash: u64,
    biome_index: u32,
}

impl PackedNameIndex {
    fn write(self, bytes: &mut Vec<u8>) {
        bytes.extend_from_slice(&self.hash.to_le_bytes());
        bytes.extend_from_slice(&self.biome_index.to_le_bytes());
    }
}
