param(
    [string]$Destination = (Join-Path $PSScriptRoot "../vendor/item-upgrade-schema")
)

$ErrorActionPreference = "Stop"
$Owner = "pmmp"
$Repository = "BedrockItemUpgradeSchema"
$PinnedCommit = "e19685d2e7e76eb7446115c556df34e5d627d072"
$Schemas = @(
    "0001_1.6_beta_to_1.6.0.json",
    "0011_1.11.4_to_1.12.0.json",
    "0021_1.16.0_to_1.16.100.json",
    "0031_1.16.100_to_1.16.200.json",
    "0041_1.16.200_to_1.17.30.json",
    "0051_1.17.40_to_1.18.0.json",
    "0061_1.18.0_to_1.18.10.json",
    "0071_1.18.10_to_1.18.30.json",
    "0081_1.18.30_to_1.19.30.34_beta.json",
    "0091_1.19.60_to_1.19.70.26_beta.json",
    "0101_1.19.70_to_1.19.80.24_beta.json",
    "0111_1.19.80_to_1.20.0.23_beta.json",
    "0121_1.20.0.23_beta_to_1.20.10.24_beta.json",
    "0131_1.20.10.24_beta_to_1.20.20.23_beta.json",
    "0141_1.20.20.23_beta_to_1.20.30.22_beta.json",
    "0151_1.20.30.22_beta_to_1.20.50.23_beta.json",
    "0161_1.20.50.23_beta_to_1.20.60.26_beta.json",
    "0171_1.20.60.26_beta_to_1.20.70.24_beta.json",
    "0181_1.20.70.24_beta_to_1.20.80.24_beta.json",
    "0191_1.20.80.24_beta_to_1.21.0.25_beta.json",
    "0201_1.21.0.25_beta_to_1.21.20.24_beta.json",
    "0211_1.21.20.24_beta_to_1.21.30.24_beta.json",
    "0221_1.21.30.24_beta_to_1.21.40.25.json",
    "0231_1.21.40.25_to_1.21.50.29_beta.json",
    "0241_1.21.50.29_beta_to_1.21.100.23_beta.json",
    "0251_1.21.100.23_beta_to_1.21.110.26_beta.json",
    "0261_1.26.10_to_1.26.20.json"
)

function Sync-File([string]$SourcePath) {
    $OutputPath = Join-Path $Destination $SourcePath
    $OutputDirectory = Split-Path -Parent $OutputPath
    New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
    $EscapedPath = ($SourcePath -split "/" | ForEach-Object { [Uri]::EscapeDataString($_) }) -join "/"
    $Uri = "https://raw.githubusercontent.com/$Owner/$Repository/$PinnedCommit/$EscapedPath"
    Invoke-WebRequest -Uri $Uri -OutFile $OutputPath
    Write-Host "downloaded $SourcePath"
}

New-Item -ItemType Directory -Force -Path $Destination | Out-Null
Sync-File "LICENSE"
Sync-File "item_legacy_id_map.json"
Sync-File "1.12.0_item_id_to_block_id_map.json"
foreach ($Schema in $Schemas) {
    Sync-File "id_meta_upgrade_schema/$Schema"
}

$SourceInfo = @"
# Vendored BedrockItemUpgradeSchema corpus

Source: $Owner/$Repository
Pinned commit: $PinnedCommit
Pinned tree: 33ea604960ce4182c4113dce948603638ce69cee
License: CC0-1.0

Generated by scripts/sync-item-upgrade-corpus.ps1. Runtime verification is performed by bedrock-world before parsing.
"@
Set-Content -LiteralPath (Join-Path $Destination "SOURCE.md") -Value $SourceInfo -Encoding utf8NoBOM
Write-Host "Pinned item upgrade corpus synchronized to $Destination"
