param(
    [string]$Destination = (Join-Path $PSScriptRoot "../vendor/blockstate-schema")
)

$ErrorActionPreference = "Stop"
$Owner = "pmmp"
$Repository = "BedrockBlockUpgradeSchema"
$PinnedCommit = "5d7889c9a1cdf9e3cd814d2a104ad69b75116ec7"
$LockPath = Join-Path $PSScriptRoot "../tests/fixtures/blockstate-schema/corpus.lock.json"
$Lock = Get-Content -LiteralPath $LockPath -Raw | ConvertFrom-Json

if ($Lock.commit -ne $PinnedCommit) {
    throw "corpus.lock.json commit $($Lock.commit) does not match pinned commit $PinnedCommit"
}

function Get-GitBlobSha1([byte[]]$Bytes) {
    $Header = [Text.Encoding]::ASCII.GetBytes("blob $($Bytes.Length)`0")
    $Hasher = [Security.Cryptography.IncrementalHash]::CreateHash(
        [Security.Cryptography.HashAlgorithmName]::SHA1
    )
    try {
        $Hasher.AppendData($Header)
        $Hasher.AppendData($Bytes)
        return [Convert]::ToHexString($Hasher.GetHashAndReset()).ToLowerInvariant()
    }
    finally {
        $Hasher.Dispose()
    }
}

function Sync-File([string]$SourcePath, [string]$ExpectedSha, [long]$ExpectedSize) {
    $OutputPath = Join-Path $Destination $SourcePath
    $OutputDirectory = Split-Path -Parent $OutputPath
    New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

    $EscapedPath = ($SourcePath -split "/" | ForEach-Object { [Uri]::EscapeDataString($_) }) -join "/"
    $Uri = "https://raw.githubusercontent.com/$Owner/$Repository/$PinnedCommit/$EscapedPath"
    Invoke-WebRequest -Uri $Uri -OutFile $OutputPath

    $Bytes = [IO.File]::ReadAllBytes($OutputPath)
    if ($Bytes.LongLength -ne $ExpectedSize) {
        throw "$SourcePath size $($Bytes.LongLength) does not match $ExpectedSize"
    }
    $ActualSha = Get-GitBlobSha1 $Bytes
    if ($ActualSha -ne $ExpectedSha) {
        throw "$SourcePath Git blob $ActualSha does not match $ExpectedSha"
    }
    Write-Host "verified $SourcePath ($ExpectedSize bytes)"
}

New-Item -ItemType Directory -Force -Path $Destination | Out-Null

Sync-File "LICENSE" "0e259d42c996742e9e3cba14c677129b2c1b6311" 7048
Sync-File $Lock.block_legacy_id_map.path $Lock.block_legacy_id_map.sha1 $Lock.block_legacy_id_map.size
foreach ($Table in $Lock.numeric_tables) {
    Sync-File $Table.path $Table.sha1 $Table.size
}
foreach ($Schema in $Lock.schemas) {
    $Path = "nbt_upgrade_schema/$($Schema.path)"
    Sync-File $Path $Schema.sha1 $Schema.size
}

$SourceInfo = @"
# Vendored BedrockBlockUpgradeSchema corpus

Source: $Owner/$Repository
Pinned commit: $PinnedCommit
Pinned tree: $($Lock.tree)
Package version: $($Lock.version)
License: $($Lock.license)

Generated by scripts/sync-blockstate-corpus.ps1. Do not edit corpus payloads manually.
"@
Set-Content -LiteralPath (Join-Path $Destination "SOURCE.md") -Value $SourceInfo -Encoding utf8NoBOM
Write-Host "Pinned BlockState corpus synchronized to $Destination"
