agreement_accepted = false

[custom_style]
theme_color = "#a0d9b6"
background_option = "default"
local_image_path = ""
network_image_url = ""
show_launch_animation = true

[launcher]
debug = false
language = "auto"
custom_appx_api = "https://raw.githubusercontent.com/LiteLDev/mc-w10-versiondb-auto-update/refs/heads/master/versions.json.min"

[launcher.download]
multi_thread = false
max_threads = 8
auto_thread_count = true

[launcher.download.proxy]
disable_all_proxy = true
use_system_proxy = false
enable_http_proxy = false
http_proxy_url = ""
enable_socks_proxy = false
socks_proxy_url = ""
enable_custom_proxy = false
custom_proxy_url = ""

[game]
inject_on_launch = true
lock_mouse_on_launch = false
reduce_pixels = 10
unlock_mouse_hotkey = "ALT"
launcher_visibility = "keep"
keep_appx_after_install = false
modify_appx_manifest = true
uwp_minimize_fix = true
