use std::{collections::BTreeMap, path::PathBuf};

use schemars::JsonSchema;
use semver::Version;
use serde::{Deserialize, Serialize};

use crate::{ApplicationId, LocaleId};

/// The complete versioned `App.toml` model.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AppManifest {
    /// Schema version used to parse and migrate the manifest.
    pub schema_version: u32,
    /// Stable application identity and display metadata.
    pub application: ApplicationMetadata,
    /// Application runtime defaults.
    #[serde(default)]
    pub runtime: RuntimeManifest,
    /// Resource pack inputs.
    #[serde(default)]
    pub resources: ResourceManifest,
    /// Localization catalog configuration owned by the application framework.
    pub i18n: I18nManifest,
    /// Declarative initial window metadata.
    #[serde(default)]
    pub windows: BTreeMap<String, WindowManifest>,
    /// Cross-platform bundle configuration.
    #[serde(default)]
    pub bundle: BundleManifest,
}

/// Stable application identity and user-visible metadata.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ApplicationMetadata {
    /// Reverse-domain application identifier.
    pub id: ApplicationId,
    /// Product display name.
    pub name: String,
    /// SemVer product version.
    pub version: Version,
    /// Organization or person publishing the application.
    pub publisher: String,
    /// Optional copyright notice embedded into platform metadata.
    #[serde(default)]
    pub copyright: Option<String>,
    /// Default locale used by platform metadata and application startup.
    pub default_locale: LocaleId,
    /// Optional output binary name without a platform extension.
    #[serde(default)]
    pub binary_name: Option<String>,
}

/// Application runtime settings independent of a physical implementation.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeManifest {
    /// Runtime provider identifier. The built-in value is `tokio`.
    #[serde(default = "default_runtime_provider")]
    pub provider: String,
    /// Deadline for service and runtime shutdown.
    #[serde(default = "default_shutdown_timeout_seconds")]
    pub shutdown_timeout_seconds: u64,
    /// Capacity of the background-to-GPUI dispatch queue.
    #[serde(default = "default_ui_queue_capacity")]
    pub ui_queue_capacity: usize,
}

impl Default for RuntimeManifest {
    fn default() -> Self {
        Self {
            provider: default_runtime_provider(),
            shutdown_timeout_seconds: default_shutdown_timeout_seconds(),
            ui_queue_capacity: default_ui_queue_capacity(),
        }
    }
}

/// Resource inputs compiled into or distributed beside an application.
#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ResourceManifest {
    /// Logical namespace used by application-owned resources.
    #[serde(default)]
    pub namespace: Option<String>,
    /// Glob patterns embedded into the application binary.
    #[serde(default)]
    pub embedded: Vec<String>,
    /// Glob patterns copied into the application bundle.
    #[serde(default)]
    pub bundled: Vec<String>,
    /// Explicit development-only directory overlays.
    #[serde(default)]
    pub development_overlays: Vec<PathBuf>,
}

/// Localization source and supported locale set.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct I18nManifest {
    /// Authoritative source locale.
    pub source_locale: LocaleId,
    /// Locales shipped by this application.
    pub locales: Vec<LocaleId>,
    /// Resource path pattern containing `{locale}`.
    #[serde(default = "default_catalog_pattern")]
    pub catalog_pattern: String,
}

/// Declarative initial window metadata.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct WindowManifest {
    /// User-visible title before runtime localization.
    pub title: String,
    /// Initial content width in logical pixels.
    pub width: u32,
    /// Initial content height in logical pixels.
    pub height: u32,
    /// Whether the user can resize the window.
    #[serde(default = "default_true")]
    pub resizable: bool,
}

/// Cross-platform bundle settings.
#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BundleManifest {
    /// Package formats generated by the bundle command.
    #[serde(default)]
    pub targets: Vec<PackageFormat>,
    /// Shared source icons and generated platform outputs.
    #[serde(default)]
    pub icons: IconManifest,
    /// Windows-specific package metadata.
    #[serde(default)]
    pub windows: WindowsBundle,
    /// macOS-specific package metadata.
    #[serde(default)]
    pub macos: MacOsBundle,
    /// Linux-specific package metadata.
    #[serde(default)]
    pub linux: LinuxBundle,
}

/// Supported package output formats.
#[derive(
    Clone, Copy, Debug, Deserialize, Eq, Hash, JsonSchema, Ord, PartialEq, PartialOrd, Serialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum PackageFormat {
    /// An unpackaged Windows executable directory.
    WindowsPortable,
    /// A signed or unsigned Windows MSIX package.
    WindowsMsix,
    /// A Windows MSI installer backend.
    WindowsMsi,
    /// A Windows NSIS installer backend.
    WindowsNsis,
    /// A macOS `.app` bundle.
    MacOsApp,
    /// A macOS disk image.
    MacOsDmg,
    /// A Linux AppImage.
    LinuxAppImage,
    /// A Debian package.
    LinuxDeb,
    /// An RPM package.
    LinuxRpm,
}

/// Shared icon source configuration.
#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IconManifest {
    /// High-resolution source image used by icon tooling.
    #[serde(default)]
    pub source: Option<PathBuf>,
    /// Optional prebuilt Windows ICO.
    #[serde(default)]
    pub windows_ico: Option<PathBuf>,
    /// Optional prebuilt macOS ICNS.
    #[serde(default)]
    pub macos_icns: Option<PathBuf>,
    /// Optional directory containing freedesktop PNG sizes.
    #[serde(default)]
    pub linux_png_directory: Option<PathBuf>,
}

/// Windows bundle metadata.
#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct WindowsBundle {
    /// Optional MSIX publisher distinguished name.
    #[serde(default)]
    pub publisher_identity: Option<String>,
    /// Minimum supported Windows build.
    #[serde(default)]
    pub minimum_version: Option<String>,
    /// Requested execution level for the generated application manifest.
    #[serde(default)]
    pub execution_level: Option<String>,
    /// Stable WiX upgrade code used by MSI package upgrades.
    #[serde(default)]
    pub upgrade_code: Option<String>,
    /// Optional certificate thumbprint used by an external signing step.
    #[serde(default)]
    pub certificate_thumbprint: Option<String>,
}

/// macOS bundle metadata.
#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct MacOsBundle {
    /// Minimum supported macOS version.
    #[serde(default)]
    pub minimum_system_version: Option<String>,
    /// Entitlements file applied during signing.
    #[serde(default)]
    pub entitlements: Option<PathBuf>,
    /// Whether hardened runtime is required.
    #[serde(default)]
    pub hardened_runtime: bool,
    /// Optional Keychain signing identity.
    #[serde(default)]
    pub signing_identity: Option<String>,
    /// Optional `notarytool` keychain profile name.
    #[serde(default)]
    pub notarization_profile: Option<String>,
}

/// Linux bundle metadata.
#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LinuxBundle {
    /// Freedesktop application categories.
    #[serde(default)]
    pub categories: Vec<String>,
    /// Optional executable command-line categories for MIME handlers.
    #[serde(default)]
    pub mime_types: Vec<String>,
}

fn default_runtime_provider() -> String {
    "tokio".to_owned()
}

fn default_catalog_pattern() -> String {
    "locales/{locale}/main.ftl".to_owned()
}

const fn default_shutdown_timeout_seconds() -> u64 {
    15
}

const fn default_ui_queue_capacity() -> usize {
    256
}

const fn default_true() -> bool {
    true
}
