#[path = "bedrock_auth_local.rs"]
pub(crate) mod bedrock_auth;
pub mod curseforge;
pub mod easytier;
pub mod inject;
pub mod levilamina;
#[cfg(target_os = "linux")]
pub(crate) mod linux_runtime;
pub mod minecraft;
#[path = "online/online.rs"]
pub mod online;
pub mod sponsors;
#[cfg(target_os = "windows")]
pub(crate) mod system_xbox_user;
pub mod ui_prefs;
pub mod version;
#[cfg(target_os = "windows")]
pub(crate) mod windows_terminal;
pub(crate) mod xbox_avatar_cache;
