use serde_json::Value;
use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=data/colors/bedrock-block-color.json");
    println!("cargo:rerun-if-changed=data/colors/bedrock-biome-color.json");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let block_json = fs::read_to_string(manifest_dir.join("data/colors/bedrock-block-color.json"))
        .expect("read block palette JSON");
    let biome_json = fs::read_to_string(manifest_dir.join("data/colors/bedrock-biome-color.json"))
        .expect("read biome palette JSON");
    let block_value = serde_json::from_str::<Value>(&block_json).expect("parse block palette JSON");
    let biome_value = serde_json::from_str::<Value>(&biome_json).expect("parse biome palette JSON");

    let mut output = String::new();
    output.push_str("// @generated by build.rs; source files live in data/colors.\n");
    output.push_str("#[derive(Clone, Copy)]\n");
    output.push_str("pub(super) struct StaticColor { pub red: u8, pub green: u8, pub blue: u8, pub alpha: u8 }\n");
    output.push_str("#[derive(Clone, Copy)]\n");
    output.push_str(
        "pub(super) struct StaticBlockColor { pub name: &'static str, pub color: StaticColor }\n",
    );
    output.push_str("#[derive(Clone, Copy)]\n");
    output.push_str("pub(super) struct StaticBiomeColor { pub id: u32, pub color: StaticColor, pub grass: StaticColor, pub foliage: StaticColor, pub water: StaticColor }\n");
    output.push_str("#[derive(Clone, Copy)]\n");
    output.push_str("pub(super) struct StaticStateRule { pub block: &'static str, pub state: &'static str, pub selector: StaticStateSelector, pub color: StaticColor }\n");
    output.push_str("#[derive(Clone, Copy)]\n");
    output.push_str("pub(super) enum StaticStateSelector { IntRange { min: i32, max: i32 }, StringValues(&'static [&'static str]) }\n");
    output.push_str("#[derive(Clone, Copy)]\n");
    output.push_str("pub(super) struct StaticVariantColor { pub block: &'static str, pub variant: &'static str, pub color: StaticColor }\n");

    write_block_colors(&mut output, &block_value);
    write_biome_colors(&mut output, &biome_value);
    write_state_rules(&mut output, &block_value);
    write_variant_colors(&mut output, &block_value);

    fs::write(out_dir.join("builtin_palette_tables.rs"), output).expect("write palette tables");
}

fn write_block_colors(output: &mut String, root: &Value) {
    output.push_str("pub(super) static BUILTIN_BLOCK_COLORS: &[StaticBlockColor] = &[\n");
    let blocks = object_at(root, "blocks");
    for (name, entry) in blocks {
        let color = color_at(entry, "default").unwrap_or_else(|| {
            panic!("block {name} is missing default color");
        });
        writeln!(
            output,
            "    StaticBlockColor {{ name: {name:?}, color: {} }},",
            static_color(color)
        )
        .expect("write generated block color");
    }
    output.push_str("];\n");
}

fn write_biome_colors(output: &mut String, root: &Value) {
    let defaults = object_at(root, "defaults");
    let grass_default = color_at_object(&defaults, "grass").expect("default grass");
    let foliage_default = color_at_object(&defaults, "leaves").expect("default foliage");
    let water_default = color_at_object(&defaults, "water").expect("default water");
    writeln!(
        output,
        "pub(super) static BUILTIN_BIOME_DEFAULT_GRASS: StaticColor = {};\n",
        static_color(grass_default)
    )
    .expect("write generated grass default");
    writeln!(
        output,
        "pub(super) static BUILTIN_BIOME_DEFAULT_FOLIAGE: StaticColor = {};\n",
        static_color(foliage_default)
    )
    .expect("write generated foliage default");
    writeln!(
        output,
        "pub(super) static BUILTIN_BIOME_DEFAULT_WATER: StaticColor = {};\n",
        static_color(water_default)
    )
    .expect("write generated water default");
    output.push_str("pub(super) static BUILTIN_BIOME_COLORS: &[StaticBiomeColor] = &[\n");
    let biomes = object_at(root, "biomes");
    for (name, entry) in biomes {
        let id = entry
            .get("id")
            .and_then(Value::as_u64)
            .and_then(|id| u32::try_from(id).ok())
            .unwrap_or_else(|| panic!("biome {name} is missing numeric id"));
        let color = color_at_any(entry, &["default", "color", "map_color", "rgba", "rgb"])
            .unwrap_or_else(|| {
                panic!("biome {name} is missing default color");
            });
        let grass = color_at(entry, "grass").unwrap_or(grass_default);
        let foliage = color_at(entry, "leaves").unwrap_or(foliage_default);
        let water = color_at(entry, "water").unwrap_or(water_default);
        writeln!(
            output,
            "    StaticBiomeColor {{ id: {id}, color: {}, grass: {}, foliage: {}, water: {} }},\n",
            static_color(color),
            static_color(grass),
            static_color(foliage),
            static_color(water)
        )
        .expect("write generated biome color");
    }
    output.push_str("];\n");
}

fn write_state_rules(output: &mut String, root: &Value) {
    output.push_str("pub(super) static BUILTIN_STATE_RULES: &[StaticStateRule] = &[\n");
    let blocks = object_at(root, "blocks");
    for (block, entry) in blocks {
        let Some(state_colors) = entry.get("state_colors").and_then(Value::as_object) else {
            continue;
        };
        for (state, rules) in sorted_object(state_colors) {
            let rules = rules
                .as_array()
                .unwrap_or_else(|| panic!("{block}.{state} state rules must be an array"));
            for rule in rules {
                let color = color_at(rule, "color").unwrap_or_else(|| {
                    panic!("{block}.{state} state rule is missing color");
                });
                if let Some(values) = rule.get("values").and_then(Value::as_array) {
                    let values = values
                        .iter()
                        .map(|value| value.as_str().expect("state value string"))
                        .collect::<Vec<_>>();
                    output.push_str("    StaticStateRule { ");
                    write!(
                        output,
                        "block: {block:?}, state: {state:?}, selector: StaticStateSelector::StringValues(&[",
                    )
                    .expect("write generated string state selector");
                    for value in values {
                        write!(output, "{value:?},").expect("write generated state value");
                    }
                    writeln!(output, "]), color: {} }},", static_color(color))
                        .expect("write generated string state rule");
                    continue;
                }
                let min = rule
                    .get("min")
                    .and_then(Value::as_i64)
                    .and_then(|value| i32::try_from(value).ok())
                    .expect("state min");
                let max = rule
                    .get("max")
                    .and_then(Value::as_i64)
                    .and_then(|value| i32::try_from(value).ok())
                    .expect("state max");
                writeln!(
                    output,
                    "    StaticStateRule {{ block: {:?}, state: {:?}, selector: StaticStateSelector::IntRange {{ min: {min}, max: {max} }}, color: {} }},\n",
                    block,
                    state,
                    static_color(color)
                )
                .expect("write generated int state rule");
            }
        }
    }
    output.push_str("];\n");
}

fn write_variant_colors(output: &mut String, root: &Value) {
    output.push_str("pub(super) static BUILTIN_VARIANT_COLORS: &[StaticVariantColor] = &[\n");
    let blocks = object_at(root, "blocks");
    for (block, entry) in blocks {
        let Some(variant_colors) = entry.get("variant_colors").and_then(Value::as_object) else {
            continue;
        };
        for (variant, color_value) in sorted_object(variant_colors) {
            let color = parse_color(color_value)
                .unwrap_or_else(|| panic!("{block}.{variant} variant color is invalid"));
            writeln!(
                output,
                "    StaticVariantColor {{ block: {block:?}, variant: {variant:?}, color: {} }},",
                static_color(color)
            )
            .expect("write generated variant color");
        }
    }
    output.push_str("];\n");
}

fn object_at<'a>(root: &'a Value, key: &str) -> BTreeMap<&'a str, &'a Value> {
    let object = root
        .get(key)
        .and_then(Value::as_object)
        .unwrap_or_else(|| panic!("missing object {key}"));
    sorted_object(object)
}

fn sorted_object(object: &serde_json::Map<String, Value>) -> BTreeMap<&str, &Value> {
    object
        .iter()
        .map(|(key, value)| (key.as_str(), value))
        .collect()
}

fn color_at(value: &Value, key: &str) -> Option<[u8; 4]> {
    value
        .as_object()
        .and_then(|object| color_at_object(&sorted_object(object), key))
}

fn color_at_any(value: &Value, keys: &[&str]) -> Option<[u8; 4]> {
    keys.iter().find_map(|key| color_at(value, key))
}

fn color_at_object(object: &BTreeMap<&str, &Value>, key: &str) -> Option<[u8; 4]> {
    object.get(key).and_then(|value| parse_color(value))
}

fn parse_color(value: &Value) -> Option<[u8; 4]> {
    let channels = value.as_array()?;
    if !(channels.len() == 3 || channels.len() == 4) {
        return None;
    }
    Some([
        parse_u8(channels.first()?)?,
        parse_u8(channels.get(1)?)?,
        parse_u8(channels.get(2)?)?,
        channels.get(3).map_or(Some(255), parse_u8)?,
    ])
}

fn parse_u8(value: &Value) -> Option<u8> {
    value
        .as_u64()
        .and_then(|channel| u8::try_from(channel).ok())
}

fn static_color(color: [u8; 4]) -> String {
    format!(
        "StaticColor {{ red: {}, green: {}, blue: {}, alpha: {} }}",
        color[0], color[1], color[2], color[3]
    )
}
