//! Explicit Minecraft Bedrock world upgrade planning and independently safe upgrade steps.
//!
//! Ordinary world reads/writes never call this code. Upgrade is a separate operation and its plan is
//! derived from the actual persisted data present in the world folder.

use crate::block::{AuthoritativeBlockStateCatalog, VanillaBlockStatePalette};
use crate::chunk::{
    SubChunkStorageWriteReport, SubChunkUpgradeWriteReport, SubChunkVersion,
    stage_paletted_subchunks_for_upgrade, stage_subchunks_as_version,
};
use crate::database::StorageOp;
use crate::entity::{ActorStorageRewriteReport, stage_world_entity_to_digp_actorprefix};
use crate::error::{BedrockWorldError, Result};
use crate::player::{SavedItemKind, read_level_dat_player};
use crate::version::GameVersion;
use crate::world::{BedrockWorld, SubChunkVersionCount, WorldFormat, WorldStorageHandle, WorldVersions};
use std::cmp::Ordering;

const LEGACY_TERRAIN_SUBCHUNKS_PER_CHUNK: usize = 8;
const LEGACY_BIOME_SAMPLES_PER_CHUNK: usize = 256;

/// One concrete data rewrite required to upgrade a world to the requested Bedrock release.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UpgradeAction {
    /// Update version-bearing `level.dat` data after all world data has been rewritten successfully.
    LevelDat,
    /// Losslessly separate `LegacyTerrain` into fixed-array SubChunks plus `Data2DLegacy`.
    LegacyTerrainToSubChunksAndData2DLegacy {
        /// Number of `LegacyTerrain` records found.
        records: usize,
        /// Explicit fixed-array SubChunk version used by the lossless split step.
        subchunk_target: SubChunkVersion,
        /// Number of SubChunk records produced by the split (`records * 8`).
        generated_subchunks: usize,
    },
    /// Merge historical `BlockExtraData` second-layer blocks into V8/V9 SubChunk storage.
    BlockExtraDataToSubChunkStorage {
        /// Number of chunk-scoped `BlockExtraData` records found.
        records: usize,
    },
    /// Rewrite persisted SubChunks to the target SubChunk version.
    SubChunks {
        /// Actual source SubChunk versions and counts already persisted in the world.
        source: Vec<SubChunkVersionCount>,
        /// Additional fixed-array SubChunks that will be produced by the preceding `LegacyTerrain` split.
        generated_from_legacy_terrain: usize,
        /// Target SubChunk version selected for the requested Bedrock release.
        target: SubChunkVersion,
    },
    /// Expand `Data2D` biome data to `Data3D` without dropping persisted fields.
    Data2DToData3D {
        /// Number of `Data2D` records found.
        records: usize,
    },
    /// Expand `Data2DLegacy` biome IDs/heights to `Data3D` after explicit saved-RGB loss approval.
    Data2DLegacyToData3D {
        /// Number of existing plus `LegacyTerrain`-generated `Data2DLegacy` records.
        records: usize,
        /// Number of these records generated by the preceding `LegacyTerrain` split.
        generated_from_legacy_terrain: usize,
    },
    /// Rewrite chunk-scoped `Entity` actor data to `digp`/`actorprefix` storage.
    EntityToDigpActorprefix {
        /// Number of chunk `Entity` records found.
        records: usize,
    },
    /// Rewrite historical saved-item identities/BlockStates in player records.
    PlayerSavedItems {
        /// Number of player records containing historical or mixed saved-item forms.
        players: usize,
    },
}

/// Persisted information that a forward upgrade cannot carry into the selected newer representation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UpgradeLoss {
    /// `Data2DLegacy` saved biome RGB bytes have no field in `Data3D`.
    SavedBiomeRgb {
        /// Number of affected `Data2DLegacy` records.
        records: usize,
        /// Number of `[red, green, blue]` samples that require explicit discard approval.
        samples: usize,
    },
}

/// Reason an upgrade target cannot be selected safely from the persisted evidence alone.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UpgradeIssue {
    /// `level.dat` did not contain a usable last-opened Bedrock version.
    MissingSourceGameVersion,
    /// The requested target is not newer than the persisted source version.
    TargetIsNotNewer,
    /// A SubChunk record had no readable version byte.
    UnversionedSubChunks {
        /// Number of affected records.
        records: usize,
    },
    /// A SubChunk version newer than the library knows was found.
    UnknownSubChunkVersion {
        /// Unknown persisted version byte.
        version: u8,
        /// Number of affected records.
        records: usize,
    },
    /// The pre-LevelDB `chunks.dat` backend is currently read-only.
    PocketChunksDatWriteNotImplemented,
    /// The target sits in the historical Caves & Cliffs experimental range where game version alone
    /// does not uniquely select V8 versus V9 persisted SubChunks.
    ExperimentalSubChunkTarget,
}

/// Complete, non-mutating upgrade plan for one world folder.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpgradePlan {
    /// Persisted source game version from `level.dat`, when present.
    pub source: Option<GameVersion>,
    /// Requested target Minecraft Bedrock version.
    pub target: GameVersion,
    /// Version/data evidence collected from the world.
    pub world: WorldVersions,
    /// Concrete rewrites required by the target.
    pub actions: Vec<UpgradeAction>,
    /// Persisted data that requires an explicit lossy decision for the selected target representation.
    pub losses: Vec<UpgradeLoss>,
    /// Conditions that prevent unambiguous target selection.
    pub issues: Vec<UpgradeIssue>,
}

impl UpgradePlan {
    /// Returns whether the requested target and persisted version evidence are unambiguous.
    #[must_use]
    pub fn is_structurally_valid(&self) -> bool {
        self.issues.is_empty()
    }

    /// Returns whether every planned representation change can preserve all persisted information.
    #[must_use]
    pub fn is_lossless(&self) -> bool {
        self.losses.is_empty()
    }
}

impl<S> BedrockWorld<S>
where
    S: WorldStorageHandle,
{
    /// Builds an explicit upgrade plan without modifying the world.
    pub fn upgrade_plan_blocking(&self, target: GameVersion) -> Result<UpgradePlan> {
        let versions = self.versions_blocking()?;
        let source = versions.game_version().cloned();
        let mut actions = Vec::new();
        let mut losses = Vec::new();
        let mut issues = Vec::new();

        match source.as_ref() {
            Some(source) if compare_game_versions(&target, source) != Ordering::Greater => {
                issues.push(UpgradeIssue::TargetIsNotNewer);
            }
            Some(_) => {}
            None => issues.push(UpgradeIssue::MissingSourceGameVersion),
        }

        if versions.world_format == WorldFormat::PocketChunksDat {
            issues.push(UpgradeIssue::PocketChunksDatWriteNotImplemented);
        }
        if versions.unversioned_subchunks != 0 {
            issues.push(UpgradeIssue::UnversionedSubChunks {
                records: versions.unversioned_subchunks,
            });
        }
        for entry in &versions.subchunks {
            if let SubChunkVersion::Unknown(version) = entry.version {
                issues.push(UpgradeIssue::UnknownSubChunkVersion {
                    version,
                    records: entry.records,
                });
            }
        }

        let target_subchunk = target_subchunk_version(&target);
        if target_subchunk.is_none() && game_at_least(&target, &[1, 16, 230, 50]) {
            issues.push(UpgradeIssue::ExperimentalSubChunkTarget);
        }

        let split_target = legacy_terrain_split_target(target_subchunk);
        let generated_legacy_subchunks = if versions.legacy_terrain_records != 0 {
            if let Some(split_target) = split_target {
                let generated_subchunks = versions
                    .legacy_terrain_records
                    .saturating_mul(LEGACY_TERRAIN_SUBCHUNKS_PER_CHUNK);
                actions.push(UpgradeAction::LegacyTerrainToSubChunksAndData2DLegacy {
                    records: versions.legacy_terrain_records,
                    subchunk_target: split_target,
                    generated_subchunks,
                });
                generated_subchunks
            } else {
                0
            }
        } else {
            0
        };

        if matches!(target_subchunk, Some(SubChunkVersion::V8 | SubChunkVersion::V9))
            && versions.block_extra_data_records != 0
        {
            actions.push(UpgradeAction::BlockExtraDataToSubChunkStorage {
                records: versions.block_extra_data_records,
            });
        }

        if let Some(target_subchunk) = target_subchunk {
            let existing_need_rewrite = versions
                .subchunks
                .iter()
                .any(|entry| entry.version != target_subchunk);
            let generated_need_rewrite = generated_legacy_subchunks != 0
                && split_target.is_some_and(|split| split != target_subchunk);
            if existing_need_rewrite || generated_need_rewrite {
                actions.push(UpgradeAction::SubChunks {
                    source: versions.subchunks.clone(),
                    generated_from_legacy_terrain: generated_legacy_subchunks,
                    target: target_subchunk,
                });
            }
        }

        if game_at_least(&target, &[1, 18, 0]) {
            if versions.data2d_records != 0 {
                actions.push(UpgradeAction::Data2DToData3D {
                    records: versions.data2d_records,
                });
            }
            let legacy_2d_records = versions
                .data2d_legacy_records
                .saturating_add(versions.legacy_terrain_records);
            if legacy_2d_records != 0 {
                actions.push(UpgradeAction::Data2DLegacyToData3D {
                    records: legacy_2d_records,
                    generated_from_legacy_terrain: versions.legacy_terrain_records,
                });
                losses.push(UpgradeLoss::SavedBiomeRgb {
                    records: legacy_2d_records,
                    samples: legacy_2d_records.saturating_mul(LEGACY_BIOME_SAMPLES_PER_CHUNK),
                });
            }
        }
        if game_at_least(&target, &[1, 18, 30]) && versions.entity_records != 0 {
            actions.push(UpgradeAction::EntityToDigpActorprefix {
                records: versions.entity_records,
            });
        }

        let historical_players = count_historical_player_items(self)?;
        if historical_players != 0 {
            actions.push(UpgradeAction::PlayerSavedItems {
                players: historical_players,
            });
        }
        actions.push(UpgradeAction::LevelDat);

        Ok(UpgradePlan {
            source,
            target,
            world: versions,
            actions,
            losses,
            issues,
        })
    }

    /// Rewrites only the persisted SubChunk container versions required by the target release.
    ///
    /// This is an independently safe storage step, not a complete game-version upgrade. It does not
    /// update BlockState schema versions, items, biomes, actors, or `level.dat`. Every affected
    /// SubChunk is parsed and encoded before any storage mutation. If one source representation cannot
    /// be written exactly as the selected target version, the entire operation fails before commit.
    pub fn upgrade_subchunk_storage_blocking(
        &self,
        target: GameVersion,
    ) -> Result<SubChunkStorageWriteReport> {
        let plan = self.upgrade_plan_blocking(target.clone())?;
        if let Some(issue) = plan.issues.first() {
            return Err(BedrockWorldError::Validation(format!(
                "SubChunk storage upgrade cannot run: {issue:?}"
            )));
        }
        let target_version = target_subchunk_version(&target).ok_or_else(|| {
            BedrockWorldError::Validation(format!(
                "Bedrock {target} does not select one unambiguous SubChunk version"
            ))
        })?;
        let (batch, report) = stage_subchunks_as_version(self.storage(), target_version)?;
        commit_upgrade_storage_batch(self, &batch)?;
        Ok(report)
    }

    /// Upgrades paletted SubChunk BlockStates with authoritative rules and writes the target game's
    /// exact persisted BlockState entries and SubChunk version.
    ///
    /// The schema catalog and vanilla palette are separate authoritative inputs: the catalog defines
    /// how an old state changes, while the palette proves the resulting state actually exists in the
    /// requested target game. The palette must be for exactly `target`, and its BlockState storage
    /// version must match the catalog output. Every affected SubChunk is fully upgraded and encoded
    /// before any database write, so one unsupported/future/missing state aborts the complete step.
    ///
    /// This path intentionally accepts only paletted source SubChunks. V0/V2-V7 numeric/fixed-array
    /// data must first be resolved through the historical numeric block tables; it is never guessed
    /// through this method.
    pub fn upgrade_paletted_subchunks_blocking(
        &self,
        target: GameVersion,
        catalog: &AuthoritativeBlockStateCatalog,
        target_palette: &VanillaBlockStatePalette,
    ) -> Result<SubChunkUpgradeWriteReport> {
        let plan = self.upgrade_plan_blocking(target.clone())?;
        if let Some(issue) = plan.issues.first() {
            return Err(BedrockWorldError::Validation(format!(
                "paletted SubChunk upgrade cannot run: {issue:?}"
            )));
        }
        if target_palette.game_version() != &target {
            return Err(BedrockWorldError::Validation(format!(
                "target vanilla BlockState palette is for Bedrock {}, requested upgrade target is {target}",
                target_palette.game_version()
            )));
        }
        let target_version = target_subchunk_version(&target).ok_or_else(|| {
            BedrockWorldError::Validation(format!(
                "Bedrock {target} does not select one unambiguous SubChunk version"
            ))
        })?;
        let (batch, report) = stage_paletted_subchunks_for_upgrade(
            self.storage(),
            target_version,
            catalog,
            target_palette,
        )?;
        commit_upgrade_storage_batch(self, &batch)?;
        Ok(report)
    }

    /// Rewrites only the world's actor storage from chunk `Entity` records to `digp`/`actorprefix`.
    ///
    /// This is an independently safe upgrade step, not a full-world upgrade. It first rebuilds the
    /// current plan, rejects only direction/backend issues relevant to Actor storage, preflights all
    /// actor references, and commits the complete Actor rewrite as one storage batch. SubChunk or
    /// biome issues do not block this operation because they are not touched.
    pub fn upgrade_actor_storage_blocking(
        &self,
        target: GameVersion,
    ) -> Result<ActorStorageRewriteReport> {
        let plan = self.upgrade_plan_blocking(target)?;
        if let Some(issue) = plan.issues.iter().find(|issue| {
            matches!(
                issue,
                UpgradeIssue::MissingSourceGameVersion
                    | UpgradeIssue::TargetIsNotNewer
                    | UpgradeIssue::PocketChunksDatWriteNotImplemented
            )
        }) {
            return Err(BedrockWorldError::Validation(format!(
                "actor storage upgrade cannot run: {issue:?}"
            )));
        }
        if !plan
            .actions
            .iter()
            .any(|action| matches!(action, UpgradeAction::EntityToDigpActorprefix { .. }))
        {
            return Ok(ActorStorageRewriteReport::default());
        }

        let (batch, report) = stage_world_entity_to_digp_actorprefix(self.storage())?;
        commit_upgrade_storage_batch(self, &batch)?;
        Ok(report)
    }
}

fn commit_upgrade_storage_batch<S>(
    world: &BedrockWorld<S>,
    batch: &crate::database::StorageBatch,
) -> Result<()>
where
    S: WorldStorageHandle,
{
    if batch.is_empty() {
        return Ok(());
    }
    let mut transaction = world.transaction();
    for op in batch.ops() {
        match op {
            StorageOp::Put { key, value } => {
                transaction.put_raw_key(key.clone(), value.clone());
            }
            StorageOp::Delete { key } => {
                transaction.delete_raw_key(key.clone());
            }
        }
    }
    transaction.commit()
}

fn count_historical_player_items<S>(world: &BedrockWorld<S>) -> Result<usize>
where
    S: WorldStorageHandle,
{
    let mut count = 0usize;
    for id in world.list_players_blocking()? {
        if let Some(player) = world.get_player_blocking(&id)?
            && matches!(
                player.saved_items,
                SavedItemKind::LegacyNumeric | SavedItemKind::Mixed
            )
        {
            count = count.saturating_add(1);
        }
    }
    let level = world.read_level_dat_blocking()?;
    if let Some(player) = read_level_dat_player(&level)?
        && matches!(
            player.saved_items,
            SavedItemKind::LegacyNumeric | SavedItemKind::Mixed
        )
    {
        count = count.saturating_add(1);
    }
    Ok(count)
}

fn legacy_terrain_split_target(target_subchunk: Option<SubChunkVersion>) -> Option<SubChunkVersion> {
    match target_subchunk {
        Some(SubChunkVersion::V0) => Some(SubChunkVersion::V0),
        Some(SubChunkVersion::V1 | SubChunkVersion::V8 | SubChunkVersion::V9) => {
            Some(SubChunkVersion::V7)
        }
        _ => None,
    }
}

fn target_subchunk_version(target: &GameVersion) -> Option<SubChunkVersion> {
    if game_at_least(target, &[1, 18, 0, 20]) {
        Some(SubChunkVersion::V9)
    } else if game_at_least(target, &[1, 16, 230, 50]) {
        None
    } else if game_at_least(target, &[1, 2, 14, 2]) {
        Some(SubChunkVersion::V8)
    } else if game_at_least(target, &[1, 2, 13]) {
        Some(SubChunkVersion::V1)
    } else if game_at_least(target, &[0, 17, 0, 1]) {
        Some(SubChunkVersion::V0)
    } else {
        None
    }
}

fn compare_game_versions(left: &GameVersion, right: &GameVersion) -> Ordering {
    compare_components(left.components(), right.components())
}

fn game_at_least(version: &GameVersion, minimum: &[i32]) -> bool {
    compare_components(version.components(), minimum) != Ordering::Less
}

fn compare_components(left: &[i32], right: &[i32]) -> Ordering {
    let len = left.len().max(right.len());
    for index in 0..len {
        let left = left.get(index).copied().unwrap_or(0);
        let right = right.get(index).copied().unwrap_or(0);
        match left.cmp(&right) {
            Ordering::Equal => {}
            other => return other,
        }
    }
    Ordering::Equal
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stable_target_subchunk_versions_are_selected_explicitly() {
        assert_eq!(
            target_subchunk_version(&GameVersion::new(vec![1, 18, 0, 20]).unwrap()),
            Some(SubChunkVersion::V9)
        );
        assert_eq!(
            target_subchunk_version(&GameVersion::new(vec![1, 17, 40]).unwrap()),
            None
        );
        assert_eq!(
            target_subchunk_version(&GameVersion::new(vec![1, 2, 14, 2]).unwrap()),
            Some(SubChunkVersion::V8)
        );
        assert_eq!(
            target_subchunk_version(&GameVersion::new(vec![1, 2, 13]).unwrap()),
            Some(SubChunkVersion::V1)
        );
    }

    #[test]
    fn legacy_terrain_split_uses_lossless_numeric_intermediate() {
        assert_eq!(
            legacy_terrain_split_target(Some(SubChunkVersion::V0)),
            Some(SubChunkVersion::V0)
        );
        assert_eq!(
            legacy_terrain_split_target(Some(SubChunkVersion::V1)),
            Some(SubChunkVersion::V7)
        );
        assert_eq!(
            legacy_terrain_split_target(Some(SubChunkVersion::V8)),
            Some(SubChunkVersion::V7)
        );
        assert_eq!(
            legacy_terrain_split_target(Some(SubChunkVersion::V9)),
            Some(SubChunkVersion::V7)
        );
    }
}
